services:
  prometheus-1:
    image: prom/prometheus:latest
    container_name: prometheus-1
    volumes:
      - ./config/prometheus-1.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"  # Host:9091 -> Container:9090

  prometheus-2:
    image: prom/prometheus:latest
    container_name: prometheus-2
    volumes:
      - ./config/prometheus-2.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"  # Host:9092 -> Container:9090

  prometheus-3:
    image: prom/prometheus:latest
    container_name: prometheus-3
    volumes:
      - ./config/prometheus-3.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9093:9090"  # Host:9093 -> Container:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana   # toto zajistí persistenci dat
      - ./config/grafana:/etc/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - ./config/homer/config.yml:/www/assets/config.yml
      - ./homer/assets:/www/assets   # mapování složky assets
    ports:
      - "8080:8080"

volumes:
  grafana-data: