{
 "title": "Prometheus",
 "description": "This is a modern 'Prometheus' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=\"$cluster\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Prometheus Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{pod=~\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "All Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\", cluster=~\"$cluster\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Targets by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TSDB Head samples appended - rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Liveness by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Target Sync by pod, scrape_job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod, scrape_job) * 1000",
     "legendFormat": "{{ pod }} - {{ scrape_job }}"
    }
   ]
  },
  {
   "title": "TSDB Rate of Compactions by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Total Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_triggered_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Triggered Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_skipped_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Skipped Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Failed Compactions"
    }
   ]
  },
  {
   "title": "Engine Query Duration by pod, slice",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prometheus_engine_query_duration_seconds{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod, slice) * 1000",
     "legendFormat": "{{ pod }} - {{ slice }}"
    }
   ]
  },
  {
   "title": "Config - Last Successful Reload by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_config_last_reload_successful{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TSDB Created & Deleted series by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_series_created_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Created series"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_head_series_removed_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Deleted series"
    }
   ]
  },
  {
   "title": "Target Scrapes Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_body_size_limit_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded body size limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_sample_limit_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded sample limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Duplicate timestamp"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_bounds_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of bounds"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of order"
    }
   ]
  },
  {
   "title": "Engine Query Count by pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_query_duration_seconds_count{pod=~\"$pod\", slice=\"inner_eval\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TSDB Head Series",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB Head Series & Chunks by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Series"
    },
    {
     "expr": "sum(prometheus_tsdb_head_chunks{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Chunks"
    }
   ]
  },
  {
   "title": "TSDB Blocks Loaded by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_blocks_loaded{pod=~\"$pod\", cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Series"
    }
   ]
  },
  {
   "title": "TSDB Reload Failures by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_reloads_failures_total{pod=~\"$pod\", cluster=~\"$cluster\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}