title: "Monitoring Dashboard"
subtitle: "Homer"

services:
  - name: "Monitoring tools"
    items:
      - name: "Prometheus 1"
        logo: "/custom-icons/prometheus.png"
        url: "http://localhost:9091"
        target: "_blank"

      - name: "Prometheus 2"
        logo: "/custom-icons/prometheus.png"
        url: "http://localhost:9092"
        target: "_blank"

      - name: "Prometheus 3"
        logo: "/custom-icons/prometheus.png"
        url: "http://localhost:9093"
        target: "_blank"

      - name: "Grafana"
        logo: "/custom-icons/grafana.png"
        url: "http://localhost:3000"
        target: "_blank"
